const DoctorsList = [
  { id: 1, name: "Dr. John Smith" },
  { id: 2, name: "Dr. Emily Johnson" },
  { id: 3, name: "Dr. Michael Brown" },
  { id: 4, name: "Dr. Sarah Davis" },
  { id: 5, name: "Dr. David Wilson" },
  { id: 6, name: "Dr. Jennifer Garcia" },
  { id: 7, name: "Dr. William Martinez" },
  { id: 8, name: "Dr. Patricia Rodriguez" },
  { id: 9, name: "Dr. Daniel Hernandez" },
  { id: 10, name: "Dr. Linda Lopez" },
  { id: 11, name: "Dr. James Gonzalez" },
  { id: 12, name: "Dr. Barbara Perez" },
  { id: 13, name: "Dr. Christopher Anderson" },
  { id: 14, name: "Dr. Elizabeth Taylor" },
  { id: 15, name: "Dr. Charles Thomas" },
  { id: 16, name: "Dr. Nancy White" },
  { id: 17, name: "Dr. Joseph Harris" },
  { id: 18, name: "Dr. Karen Clark" },
  { id: 19, name: "Dr. Steven Lewis" },
  { id: 20, name: "Dr. Michelle Robinson" },
  // { id: 21, name: "Dr. Anthony Hall" },
  // { id: 22, name: "Dr. Jessica Allen" },
  // { id: 23, name: "Dr. Matthew Young" },
  // { id: 24, name: "Dr. Olivia King" },
  // { id: 25, name: "Dr. Andrew Wright" },
  // { id: 26, name: "Dr. Laura Scott" },
  // { id: 27, name: "Dr. Robert Green" },
  // { id: 28, name: "Dr. Jessica Adams" },
  // { id: 29, name: "Dr. Brian Baker" },
  // { id: 30, name: "Dr. Samantha Nelson" },
  // { id: 31, name: "Dr. Justin Carter" },
  // { id: 32, name: "Dr. Megan Mitchell" },
  // { id: 33, name: "Dr. Tyler Perez" },
  // { id: 34, name: "Dr. Emily Roberts" },
  // { id: 35, name: "Dr. Kevin Turner" },
  // { id: 36, name: "Dr. Rebecca Phillips" },
  // { id: 37, name: "Dr. Eric Campbell" },
  // { id: 38, name: "Dr. Rachel Parker" },
  // { id: 39, name: "Dr. George Edwards" },
  // { id: 40, name: "Dr. Amy Collins" },
  // { id: 41, name: "Dr. Charles Stewart" },
  // { id: 42, name: "Dr. Jessica Sanchez" },
  // { id: 43, name: "Dr. Ronald Morris" },
  // { id: 44, name: "Dr. Katherine Rogers" },
  // { id: 45, name: "Dr. Timothy Reed" },
  // { id: 46, name: "Dr. Dorothy Cook" },
  // { id: 47, name: "Dr. Brian Morgan" },
  // { id: 48, name: "Dr. Patricia Bell" },
  // { id: 49, name: "Dr. Daniel Murphy" },
  // { id: 50, name: "Dr. Sandra Cooper" },
];

export default DoctorsList;
export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
];
export const bloodGroupOptions = [
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
];

export const department = [
  { value: "Cardiology", label: "Cardiology" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "General Surgery", label: "General Surgery" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Obstetrics and Gynecology (OB/GYN)", label: "Obstetrics and Gynecology (OB/GYN)" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Radiology", label: "Radiology" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Otolaryngology (ENT) ", label: "Otolaryngology (ENT) " },
  { value: "Infectious Disease", label: "Infectious Disease" },
  { value: "Gastroenterology", label: "Gastroenterology" },
];